name: new continuous-integration-backend
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install pipenv 
        run: pip install pipenv

      - name: Install dependencies
        run: cd starter/backend && pipenv install --dev

      - name: Test pipenv
        run: cd  /home/runner/work/test4/test4/starter/backend/ && pipenv run lint

  test:
    runs-on: ubuntu-latest    
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install pipenv 
        run: pip install pipenv

      - name: Install dependencies
        run: cd  /home/runner/work/test4/test4/starter/backend/ && pipenv install --dev

      - name: Test pipenv
        run: cd starter/backend && pipenv run test

  build:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install pipenv 
        run: pip install pipenv

      - name: Install dependencies
        run: cd starter/backend && pipenv install

      - name: Build the image
        run:  cd starter/backend && docker build --tag mp-backend:latest .

      - name: Run the image
        run: docker run -p 5000:5000 --name mp-backend -d mp-backend  



